'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5420
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class CNWG020

    '''<summary>
    '''Form1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btn_refresh コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_refresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_back コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_back As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_TPJ コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_TPJ As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Change コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_Change As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonBack コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ButtonBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_release コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_release As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_Pos コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents txt_Pos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_call コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbl_call As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''call1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''call2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''call3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''call4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''call5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''call6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents call6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''orderstatus1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderstatus2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderstatus3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderstatus4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderstatus5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderstatus6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents orderstatus6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_table1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table8 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table9 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table10 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table10 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table11 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table12 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table12 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table13 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table13 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table14 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table14 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table15 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table15 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table16 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table17 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table17 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table18 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table18 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table19 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table19 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table20 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table20 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table21 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table21 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table22 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table22 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table23 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table23 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table24 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table24 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table25 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table25 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table26 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table26 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table27 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table27 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table28 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table28 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table31 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table31 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table32 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table32 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table41 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table41 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table42 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table42 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table51 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table51 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table52 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table52 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table53 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table53 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table54 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table54 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table61 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table61 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table62 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table62 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table71 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table71 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table72 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table72 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table73 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table73 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table74 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table74 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table75 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table75 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table76 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table76 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table77 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table77 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table78 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table78 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table79 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table79 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table80 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table80 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table81 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table81 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table82 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table82 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table83 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table83 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table84 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table84 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table85 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table85 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table86 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table86 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table87 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table87 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table88 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table88 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table89 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table89 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table158 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table158 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table159 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table159 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table160 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table160 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table161 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table161 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table162 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table162 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table163 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table163 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table164 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table164 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table165 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table165 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table166 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table166 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table167 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table167 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table168 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table168 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table169 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table169 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table170 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table170 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table171 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table171 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table172 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table172 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table173 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table173 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table174 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table174 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table175 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table175 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table176 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table176 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table177 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table177 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table178 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table178 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table179 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table179 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_table180 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_table180 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_Msg コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbl_Msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Textbox5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Textbox5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Textbox9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Textbox10 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents Textbox10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdn_btn_table1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table3 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table6 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table8 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table9 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table9 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table10 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table10 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table11 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table12 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table12 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table13 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table13 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table14 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table14 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table15 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table15 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table16 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table17 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table17 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table18 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table18 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table19 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table19 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table20 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table20 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table21 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table21 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table22 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table22 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table23 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table23 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table24 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table24 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table25 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table25 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table26 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table26 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table27 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table27 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table28 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table28 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table31 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table31 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table32 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table32 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table41 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table41 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table42 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table42 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table51 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table51 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table52 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table52 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table53 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table53 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table54 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table54 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table61 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table61 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table62 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table62 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table71 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table71 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table72 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table72 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table73 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table73 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table74 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table74 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table75 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table75 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table76 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table76 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table77 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table77 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table78 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table78 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table79 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table79 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table80 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table80 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table81 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table81 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table82 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table82 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table83 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table83 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table84 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table84 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table85 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table85 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table86 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table86 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table87 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table87 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table88 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table88 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table89 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table89 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table158 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table158 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table159 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table159 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table160 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table160 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table161 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table161 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table162 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table162 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table163 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table163 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table164 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table164 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table165 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table165 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table166 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table166 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table167 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table167 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table168 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table168 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table169 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table169 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table170 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table170 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table171 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table171 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table172 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table172 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table173 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table173 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table174 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table174 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table175 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table175 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table176 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table176 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table177 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table177 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table178 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table178 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table179 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table179 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdn_btn_table180 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hdn_btn_table180 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_CLOSURE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btn_CLOSURE As Global.System.Web.UI.WebControls.Button
End Class
